---
- name: k8s demo
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: create k8s secret mysecret
      kubernetes.core.k8s:
        src: mysecret.yaml
        state: present
